import { StyleSheet } from "react-native";
import { fontFamilies, fontSizes } from "./typography";

export const baseStyles = StyleSheet.create({
	rootTab: {
		height: 86,
		flexDirection: "row",
		alignItems: "center",

		position: "absolute",
		borderRadius: 70,
		paddingTop: 5,
		marginHorizontal: 15,
		paddingHorizontal: 14,
		backgroundColor: "#FFFFFF",

		shadowColor: "#1a1a1a",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.1,
		shadowRadius: 4,
		elevation: 5,
	},
	homeTab: {
		height: "100%",
		width: "100%",
		backgroundColor: "#FFFFFF",
		paddingHorizontal: 20,
		paddingTop: 20,
		paddingBottom: 50,
	},

	homeHeader: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		marginBottom: 30,
	},

	user: {
		fontFamily: fontFamilies.semiBold,
		color: "#FE8C00",
		marginBottom: 6,
		fontSize: fontSizes.xs,
	},
	userHeader: {
		flexDirection: "row",
		alignItems: "center",
		gap: 4,
	},
	userName: {
		fontFamily: fontFamilies.bold,
		color: "#181C2E",
		fontSize: fontSizes.md,
	},
	cart: {
		height: 40,
		width: 40,
		position: "relative",
		alignItems: "center",
		justifyContent: "center",
		borderRadius: 50,
		backgroundColor: "#181C2E",
	},
	arrow: { height: 10, width: 14 },
	bag: {
		height: 20,
		width: 20,
	},
	badge: {
		width: 20,
		height: 20,
		position: "absolute",
		top: -8,
		right: -5,
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: "#FF7622",
		borderRadius: 50,
	},
	badgeText: {
		color: "#FFFFFF",
	},
	profileTab: {
		height: "100%",
		width: "100%",
		padding: 20,
	},
	profileHeader: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		marginBottom: 36,
	},
	profileIcon: { height: 20, width: 20 },
	profileHeaderText: {
		fontFamily: fontFamilies.semiBold,
		fontSize: fontSizes.lg,
		color: "#181C2E",
	},
	profileAvatarContainer: {
		alignItems: "center",
		marginBottom: 30,
	},
	profileAvatar: {
		height: 100,
		width: 100,
	},
	profileInfo: {
		backgroundColor: "#FFFFFF",
		width: "100%",
		paddingVertical: 20,
		paddingHorizontal: 14,
		borderRadius: 20,
	},
	profileItem: {
		flexDirection: "row",
		alignItems: "center",
		gap: 10,
		paddingTop: 20,
		paddingHorizontal: 14,
		backgroundColor: "#FFFFFF",
	},
	profileItemFirst: {
		borderTopLeftRadius: 20,
		borderTopRightRadius: 20,
	},
	profileItemLast: {
		borderBottomLeftRadius: 20,
		borderBottomRightRadius: 20,
		paddingBottom: 20,
	},
	profileIconWrapper: {
		width: 48,
		height: 48,
		backgroundColor: "#fe8c001a",
		borderRadius: 50,
		alignItems: "center",
		justifyContent: "center",
		borderWidth: 2,
		borderColor: "#fe8c001a",
	},
	profileLabel: {
		color: "#6A6A6A",
		fontFamily: fontFamilies.medium,
		fontSize: fontSizes.sm,
		marginBottom: 4,
	},
	profileValue: {
		color: "#181C2E",
		fontFamily: fontFamilies.semiBold,
		fontSize: fontSizes.md,
	},
	profileButtons: {
		gap: 20,
		marginTop: 30,
	},
	profileEditButton: {
		height: 48,
		width: "100%",
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: "#fe8c001a",
		borderRadius: 100,
		borderWidth: 1,
		borderColor: "#FE8C00",
	},
	profileEditText: {
		fontFamily: fontFamilies.semiBold,
		fontSize: fontSizes.md,
		color: "#FE8C00",
	},
	profileLogoutButton: {
		height: 48,
		width: "100%",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		gap: 8,
		backgroundColor: "#f1414119",
		borderRadius: 100,
		borderWidth: 1,
		borderColor: "#F14141",
	},
	profileLogoutText: {
		fontFamily: fontFamilies.semiBold,
		fontSize: fontSizes.md,
		color: "#F14141",
	},
	logoutIcon: {
		width: 24,
		height: 24,
	},
	searchTab: {
		height: "100%",
		width: "100%",
		paddingHorizontal: 20,
		paddingTop: 20,
		paddingBottom: 100,
	},
	inputContainer: {
		width: "100%",
		height: 52,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		backgroundColor: "#FFFFFF",
		borderRadius: 40,
		paddingHorizontal: 20,

		// iOS shadow
		shadowColor: "#000",
		shadowOpacity: 0.12,
		shadowRadius: 10,
		shadowOffset: {
			width: 0,
			height: 6,
		},

		// Android shadow
		elevation: 10,
	},
	input: {
		flex: 1,
		fontFamily: fontFamilies.bold,
		fontSize: fontSizes.md,
		color: "#181C2E",
	},
	searchIcon: {
		width: 20,
		height: 20,
	},
	emptyState: {
		alignItems: "center",
		gap: 14,
		marginTop: 80,
	},
	emptyStateImage: {
		width: 172,
		height: 128,
	},
	emptyStateTitle: {
		fontFamily: fontFamilies.bold,
		fontSize: fontSizes.lg,
		color: "#181C2E",
		textAlign: "center",
	},
	emptyStateText: {
		fontFamily: fontFamilies.medium,
		fontSize: fontSizes.md,
		color: "#878787",
		textAlign: "center",
	},
	categories: {
		marginVertical: 28,
	},
	category: {
		paddingVertical: 14,
		paddingHorizontal: 24,
		marginRight: 10,
		backgroundColor: "#FFFFFF",
		borderRadius: 25,
	},
	categoryIsActive: {
		backgroundColor: "#FE8C00",
	},
	categoryTextActive: {
		color: "#FFFFFF",
	},
	categoryText: {
		color: "#878787",
		fontFamily: fontFamilies.semiBold,
		fontSize: fontSizes.md,
	},
	loader: {
		marginTop: 200,
	},
	errorImage: {
		height: 300,
		width: 350,
	},
	errorText: {
		color: "#181C2E",
		fontFamily: fontFamilies.semiBold,
		fontSize: fontSizes.md,
		textAlign: "center",
	},
	searchResults: {
		marginTop: 100,
		justifyContent: "space-between",
	},
	cartHeader: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		marginBottom: 20,
	},
	changeLocation: {
		height: 32,
		width: 130,
		borderRadius: 100,
		alignItems: "center",
		justifyContent: "center",
		borderColor: "#FE8C00",
		borderWidth: 1,
	},
	locationText: {
		fontFamily: fontFamilies.bold,
		fontSize: fontSizes.xs,
		color: "#FE8C00",
	},
	cartItemsContainer: {
		gap: 20,
		marginTop: 10,
		marginBottom: 30,
	},
	emptyCart: {
		marginTop: 60,
		alignItems: "center",
		gap: 20,
	},
	emptyCartText: {
		fontFamily: fontFamilies.bold,
		fontSize: fontSizes.lg,
		color: "#181C2E",
		textAlign: "center",
	},
	startShopping: {
		height: 48,
		width: "50%",
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: "#fe8c00d8",
		borderRadius: 30,
	},
	startShoppingText: {
		fontFamily: fontFamilies.semiBold,
		fontSize: fontSizes.md,
		color: "#FFFFFF",
	},
});
